<?php

declare(strict_types=1);

namespace OCA\SouveraMail\Listeners;

use OCA\SouveraMail\AppInfo\Application;
use OCA\SouveraMail\Service\QuotaService;
use OCP\AppFramework\Http\Events\BeforeTemplateRenderedEvent;
use OCP\EventDispatcher\Event;
use OCP\EventDispatcher\IEventListener;
use OCP\IGroupManager;
use OCP\IURLGenerator;
use OCP\IUserSession;
use OCP\Util;

/**
 * Injects the Souvera Mail quota entry into Nextcloud's global user
 * menu (the popover that opens when you click your avatar in the
 * top-right of every NC page).
 *
 * Loaded on EVERY NC page render (not just inside the mail app),
 * because the operator asked for the quota to be visible from
 * anywhere in Nextcloud — Files, Calendar, Settings, everywhere.
 *
 * Guards:
 *   - Only for authenticated users (no login-flow injection).
 *   - Only for members of `souvera-users` (matches the app-visibility
 *     restriction from v0.13.0 — if you don't have Mail, you don't
 *     need a Mail quota entry either).
 *   - Only for HTML page renders (skip API responses, WebDAV, etc.).
 *
 * The script uses a `data-endpoint` attribute to know where to
 * fetch the quota JSON. That URL is generated by `IURLGenerator`
 * so it works under sub-paths and reverse proxies.
 *
 * @implements IEventListener<Event>
 */
class NcHeaderMenuQuotaListener implements IEventListener
{
    public function __construct(
        private IUserSession $userSession,
        private IGroupManager $groupManager,
        private IURLGenerator $urlGenerator,
        private QuotaService $quotaService,
    ) {
    }

    public function handle(Event $event): void
    {
        if (!($event instanceof BeforeTemplateRenderedEvent)) {
            return;
        }

        // Skip if the current render is not an HTML "user" page. The
        // event fires for API renders too — we don't want to append
        // scripts to a WebDAV response header.
        try {
            $renderAs = $event->getResponse()->getRenderAs();
        } catch (\Throwable $e) {
            $renderAs = '';
        }
        if ($renderAs !== 'user' && $renderAs !== '') {
            return;
        }

        $user = $this->userSession->getUser();
        if ($user === null) {
            return;
        }
        if (!$this->groupManager->isInGroup($user->getUID(), Application::RESTRICTED_GROUP_ID)) {
            return;
        }

        // Fast path: if the quota service is not configured (Stalwart
        // missing / OIDC not set up yet), skip injecting the script
        // entirely — no menu entry, no console error, no noise.
        if (!$this->quotaService->isAvailable()) {
            return;
        }

        $endpoint = $this->urlGenerator->linkToRoute(
            Application::APP_ID . '.quota.index'
        );

        // Emit an inline <script> tag with the endpoint baked in as a
        // data-attribute, then append the actual loader. This is the
        // simplest way to hand a server-generated URL to a script
        // that must live outside the standard `<html>` bundle.
        Util::addHeader('script', [
            'type' => 'application/json',
            'id' => 'souvera-mail-quota-config',
        ], (string) \json_encode(['endpoint' => $endpoint]));

        Util::addScript(Application::APP_ID, 'nc-header-menu-quota', 'core');
    }
}
